version: "3"

services:
  nest:
    image: "node:11.10"
    user: "node"
    working_dir: /home/node/app
    environment:
      - PORT=7777
      - NODE_ENV=development
    volumes:
      - ./:/home/node/app
    ports:
      - "7777:7777"
    command: "npm run start:dev"