version: "3"

services:
  nest:
    image: "node:11.10"
    user: "node"
    working_dir: /home/node/app
    env_file: ".env"
    volumes:
      - ./:/home/node/app
    ports:
      - "7777:7777"
    command: "npm run start:dev"

  db:
    image: postgres
    env_file: ".env"

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080